### ISSUE TITLE
WebJars example?

### ISSUE THREAD

**Issue by kev009** [huntc/sbt-uglify#1]
Can you use this to flatten multiple WebJar JavaScript files into one?

**Comment by huntc** [comment]
That's what it should d by default. :-) Please let me know otherwise.

**Comment by kev009** [comment]
I'm pretty dense but I don't understand this magic.

Plugin is specified and Build.sbt adds:
pipelineStages := Seq(uglify, digest, gzip)

Do I just do something like '@routes.Assets.at(javascripts/main.min.js)' in my template?

What kind of magic is this to walk the lib/ path?  And the javascripts path?  Do I have to actually create the main.min.js file in app/assets/javascripts and specify the includes in there?

**Comment by huntc** [comment]
> What kind of magic is this to walk the lib/ path? And the javascripts path? Do I have to actually create the main.min.js file in app/assets/javascripts and specify the includes in there?

WebJars are extracted to the file system (in the target folder) and made available via the public/lib folder. As such all webjars should be available to uglify.

> Do I just do something like '@routes.Assets.at(javascripts/main.min.js)' in my template?

Yes. At present Play's reverse router does not do that for you i.e. this would be ideal:

``` scala
@routes.Assets.at(javascripts/main.js)
```

...and if there was a main.min.js available the reverse router would give you that. 

This PR will make things a little easier in (hopefully) Play 2.3.1:

https://github.com/playframework/playframework/pull/2973

**Comment by kev009** [comment]
I'm still confused, sorry :(.  This PR would imply it's on a file .min basis, whereas my original question was about mashing files together to also save request RTTs.
- How does it have any idea what JS files I care about and which ones I don't?
- It only combines during 'stage', not dev?

**Comment by huntc** [comment]
1. It combines just during prod (it can go dev, but your dev would slow down of course).
2. By default it takes all js files but you can filter those if required.

Please feel free to keep asking questions! This is useful to me also.

**Comment by kev009** [comment]
This would seem problematic, for instance in my container template I would have one script src tag to include the single JS file.  Except that doesn't exist during dev.  Maybe during dev, a concat should run, but without optimization for speed?

A future request when you have time are either cookbook style docs or example activator projects of this and sbt-rjs showing a full invocation.  It's hard for me to bridge the two worlds of the JS docs and the currently light sbt-web docs and I bet I won't be the last.  It's probably simple when you have the right context, but I'm not an expert on either so it seems opaque right now.

**Comment by kev009** [comment]
Do you want to hop on a video call and I'll give you my idiot's perspective why it's fresh in mind?  I ended up figuring out sbt-rjs after quite a bit of suffering.  May help for doco.

**Comment by huntc** [comment]
Hi Kevin - I'd love to but I'm right in the middle of ScalaDays at the moment. If you'd like to raise a PR with an update to doco then that'd be great meanwhile. Thanks.
